apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ejkv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-ejkv@sha256:db1b08470c5d75ae28d6a5c8cb6eec62036fb4075523b82b3244a2a6a071418c
        name: my-nodejs
        resources: {}
status: {}
